{
    Package
    {
        BSCat.m
        BSFreeCat.m
        CoxeterUtil.m
        IntersectionForms.m
        IO.m
        ParabolicCoxeter.m
        QPDIndec.m
        SparseMat.m
        StdCat.m
        IdemCalcHelpers.m
        IdemCalc.m
    }
    IHecke
    {
        +IHecke.spec
    }
}
